// Extension registry — REGENERATED by build-ext.sh at image build when
// ext-rust/ crates exist (DEC-18). Each ext crate exposes
// `pub fn router() -> axum::Router` and is nested under /x/{crate-name},
// inside the same token gate.
//
// Default: no extensions.

pub fn mount(r: axum::Router) -> axum::Router {
    r
}
