// Controlled browser fixtures only. No live service or project mutations.
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const {createRequire}=require('node:module');const {chromium}=process.env.SIGIL_PLAYWRIGHT_PACKAGE?createRequire(process.env.SIGIL_PLAYWRIGHT_PACKAGE)('playwright'):require('playwright');
const root=process.env.SIGIL_ASSETS_DIR||path.resolve(__dirname,'../src/browser/assets');
const output=process.env.SIGIL_SCREENSHOTS||path.resolve('outputs');fs.mkdirSync(output,{recursive:true});
const project=n=>({name:n,display_name:n==='atlas'?'Atlas':n==='beacon'?'Beacon':n,description:n==='atlas'?'Research workspace for the next release':'An independent project',session_count:n==='atlas'?1:0,repository_revision:'abc123abcdef',observed_revision:'abc123abcdef',setup:{state:'ready',observed_at:1789012800,stale:false},capabilities:{ide:{desired:true,state:'pending',reason:'ide_adapter_not_configured'},workspace:{state:'ready'},memory:{state:'pending',reason:'memory_adapter_not_configured'}},app:{state:'not_deployed',runtime:{state:'unknown',reason:'not_probed'}},jobs:{items:[],total:0},sessions:{items:[],total:0},attention:{items:[],total:0},activity:{items:[],total:0},observed_at:1789012800});
const fixture={auth:true,error:false,delay:0,mutations:0,items:[],projects:[project('atlas'),project('beacon'),project('cinder')],session:{identity:{display_name:'Alex · fixture'},actor:{driver:'human:synthetic',role:'admin'},csrf_token:'synthetic-csrf',features:{work_items:true,project_creation:true}}};
const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,'http://fixture');let body='';for await(const chunk of req)body+=chunk;
 const reply=(value,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};
 if(u.pathname==='/browser/session')return reply(fixture.auth?fixture.session:{error:'login_required'},fixture.auth?200:401);
 if(u.pathname.startsWith('/browser/api/')){
  if(!fixture.auth)return reply({error:'login_required'},401);if(fixture.error)return reply({error:'fixture_unavailable'},503);
  if(req.method!=='GET'){fixture.mutations++;assert.equal(req.headers['x-sigil-csrf'],'synthetic-csrf');}
  if(u.pathname==='/browser/api/overview'){const data={observed_at:1789012800,inventory_revision:fixture.churn&&Number(u.searchParams.get('offset'))>0?'changed-membership':JSON.stringify(fixture.projects.map(p=>p.name)),projects:{items:fixture.projects.slice(Number(u.searchParams.get('offset')||0),Number(u.searchParams.get('offset')||0)+100),total:fixture.projects.length,next_offset:Number(u.searchParams.get('offset')||0)+100<fixture.projects.length?Number(u.searchParams.get('offset')||0)+100:null},attention:{items:[{project:'atlas',severity:'warning',reason:'repository_pending',source:'project:atlas/setup'}],total:1},counts:{projects:3,sessions:1,attention:1}};return reply(data);}
  if(u.pathname==='/browser/api/projects')return reply({name:JSON.parse(body).name,state:'registered'},201);
  if(u.pathname.includes('/work-items')){
   const id=u.pathname.split('/')[6];const b=body?JSON.parse(body):null;
   if(req.method==='POST'){let item=fixture.items.find(i=>i.id===b.id);if(!item){item={...b.fields,id:b.id,project:'atlas',revision:1,creator:'human:synthetic',editor:'human:synthetic',created_at:1789012800,updated_at:1789012800,audit:[]};fixture.items.unshift(item);}return reply(item,201);}
   if(req.method==='PATCH'){const item=fixture.items.find(i=>i.id===id);if(item.revision!==b.expected_revision)return reply({error:'work_item_revision_conflict'},409);Object.assign(item,b.fields,{revision:item.revision+1});return reply(item);}
   if(id)return reply(fixture.items.find(i=>i.id===id)||{},fixture.items.some(i=>i.id===id)?200:404);
   const offset=Number(u.searchParams.get('offset')||0),limit=20;return reply({items:fixture.items.slice(offset,offset+limit),total:fixture.items.length,offset,limit,next_offset:offset+limit<fixture.items.length?offset+limit:null});
  }
  const name=decodeURIComponent(u.pathname.split('/')[4]);const row=fixture.projects.find(p=>p.name===name);if(fixture.delay&&name==='atlas')await new Promise(r=>setTimeout(r,fixture.delay));return reply(row||{error:'unknown_project'},row?200:404);
 }
 const asset=u.pathname.startsWith('/browser/assets/')?u.pathname.split('/').pop():'index.html';const content=fs.readFileSync(path.join(root,asset));res.writeHead(200,{'content-type':asset.endsWith('.js')?'text/javascript':asset.endsWith('.css')?'text/css':'text/html'});res.end(content);
}catch(e){res.writeHead(500);res.end(String(e));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,...(process.env.SIGIL_BROWSER_EXECUTABLE?{executablePath:process.env.SIGIL_BROWSER_EXECUTABLE}:{})});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(5000);page.on('pageerror',e=>{throw e;});await page.goto(base);await page.getByRole('heading',{name:'Overview',exact:true}).waitFor({timeout:5000});
await page.getByRole('link',{name:'Atlas',exact:true}).last().waitFor();
assert.equal(await page.locator('img').count(),0,'malicious project text must stay text');
await page.screenshot({path:path.join(output,'dashboard-desktop.png'),fullPage:true});
fixture.projects[2].description='<img src=x onerror=alert(1)>';await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('<img src=x onerror=alert(1)>',{exact:true}).waitFor();assert.equal(await page.locator('img').count(),0);fixture.projects[2].description='An independent project';
for(let i=0;i<110;i++)fixture.projects.push(project('inventory-'+i));fixture.projects.push(project('beyond-first-page'));await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('1–20 of 114',{exact:true}).waitFor();await page.getByLabel('Search projects').fill('beyond-first-page');await page.getByRole('link',{name:'beyond-first-page',exact:true}).waitFor();assert.equal(await page.locator('tbody tr').count(),1);fixture.churn=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText(/The project inventory changed during refresh/).waitFor();await page.getByRole('link',{name:'beyond-first-page',exact:true}).waitFor();fixture.churn=false;fixture.projects.splice(3);await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('No projects match these filters.',{exact:true}).waitFor();
await page.getByLabel('Search projects').fill('beacon');assert.equal(await page.locator('tbody tr').count(),1);await page.getByLabel('Search projects').fill('');
await page.getByLabel('Show',{exact:true}).selectOption('working');assert.equal(await page.locator('tbody tr').count(),1);await page.getByLabel('Show',{exact:true}).selectOption('all');
fixture.projects.push(project('newly-registered'));await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('link',{name:'newly-registered',exact:true}).waitFor();
fixture.error=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText(/Showing stale data/).waitFor();assert.equal(await page.getByRole('link',{name:'Beacon',exact:true}).count(),1);fixture.error=false;
await page.getByRole('link',{name:'New project',exact:true}).click();await page.getByLabel('Project name').fill('INVALID');await page.getByRole('button',{name:'Create project',exact:true}).click();assert.equal(fixture.mutations,0);await page.getByLabel('Project name').fill('fresh-project');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByText('Project registered.',{exact:false}).waitFor();assert.equal(fixture.mutations,1);
await page.goto(base+'/ui/projects/atlas/pending');await page.getByRole('heading',{name:'Atlas',exact:true}).waitFor();await page.getByLabel('Title',{exact:true}).fill('Review deployment');await page.getByLabel('Description',{exact:true}).fill('A draft that must survive');await page.getByRole('button',{name:'Refresh',exact:true}).click();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),'A draft that must survive');
await page.getByRole('link',{name:'Workspace',exact:true}).click();await page.goBack();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),'A draft that must survive');
fixture.auth=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('link',{name:'Sign in in another tab'}).waitFor();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),'A draft that must survive');assert.equal(await page.getByRole('link',{name:'Sign in in another tab'}).getAttribute('target'),'_blank');const before=fixture.mutations;fixture.auth=true;await page.getByRole('button',{name:'Check sign-in'}).click();await page.getByText(/Signed in. Review your draft/).waitFor();assert.equal(fixture.mutations,before,'sign-in must never replay a mutation');
await page.getByRole('button',{name:'Save work item',exact:true}).click();await page.getByText('Saved revision 1.',{exact:true}).waitFor();assert.equal(fixture.items.length,1);
fixture.items[0].revision=2;await page.getByLabel('Description',{exact:true}).fill('My conflicted draft');await page.getByRole('button',{name:'Save work item',exact:true}).click();await page.getByText(/Someone changed this item/).waitFor();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),'My conflicted draft');
await page.getByRole('button',{name:'Load latest revision',exact:true}).click();await page.getByRole('button',{name:'Use latest revision for this draft'}).click();await page.getByRole('button',{name:'Save work item',exact:true}).click();await page.getByText('Saved revision 3.',{exact:true}).waitFor();await page.getByText(/Revision 3. Updated/).waitFor();
for(let i=0;i<21;i++)fixture.items.push({id:`fixture-${i}`,title:`Follow-up ${i}`,state:'open',revision:1,updated_at:1789012800});await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('1–20 of 22',{exact:true}).waitFor();await page.locator('#work-items').getByRole('button',{name:'Next',exact:true}).click();await page.getByText('21–22 of 22',{exact:true}).waitFor();
await page.getByRole('button',{name:'Follow-up 19',exact:true}).focus();await page.evaluate(()=>document.getElementById('refresh').click());await page.waitForResponse(r=>r.url().includes('/work-items?'));await page.waitForTimeout(50);assert.equal(await page.getByRole('button',{name:'Follow-up 19',exact:true}).evaluate(e=>e===document.activeElement),true,'poll keeps focused work-item selection');
await page.getByLabel('Description',{exact:true}).focus();await page.getByLabel('Description',{exact:true}).press('End');await page.evaluate(()=>document.getElementById('refresh').click());assert.equal(await page.getByLabel('Description',{exact:true}).evaluate(e=>e===document.activeElement),true);
await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'dashboard-work-items.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.equal(await page.locator('.tabs [aria-current]').evaluate(e=>{const a=e.getBoundingClientRect(),n=e.parentElement.getBoundingClientRect();return a.left>=n.left-1&&a.right<=n.right+1;}),true,'active tab visible on mobile');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'dashboard-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile shell must not overflow');
fixture.delay=600;await page.goto(base+'/ui/projects/atlas/overview');await page.getByRole('link',{name:'Projects',exact:true}).click();await page.getByRole('heading',{name:'Projects',exact:true,level:1}).waitFor();await page.waitForTimeout(800);assert.equal(await page.getByRole('heading',{name:'Projects',exact:true,level:1}).count(),1,'late detail must not replace navigation');
await page.goto(base+'/ui/overview');await page.getByRole('link',{name:'Beacon',exact:true}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overview has no page overflow');await page.screenshot({path:path.join(output,'dashboard-mobile-overview.png'),fullPage:true});
fixture.auth=false;await page.goto(base);await page.getByRole('link',{name:'Sign in in another tab'}).waitFor();assert.equal(await page.locator('tbody tr').count(),0);
console.log('PASS: fixture UI: login, live rows, search/filter, new-project validation/create, stale data, navigation/back, draft/focus retention, expiry/recheck without replay, work-item create/conflict/explicit revision, pagination, malicious text, delayed navigation, desktop/mobile screenshots');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
