// Deterministic UI review regressions. Synthetic loopback API and actual assets only.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {createRequire}=require('node:module');
const {chromium}=process.env.SIGIL_PLAYWRIGHT_PACKAGE?createRequire(process.env.SIGIL_PLAYWRIGHT_PACKAGE)('playwright'):require('playwright');
const root=process.env.SIGIL_ASSETS_DIR||path.resolve(__dirname,'../src/browser/assets');
let rows=[],gates=new Map(),writes=[];
const row=(id,title)=>({id,title,description:'initial',state:'open',owner:'',source_link:'',revision:1,created_at:1,updated_at:1,audit:[]});
function hold(key){let release,started;const promise=new Promise(r=>release=r),seen=new Promise(r=>started=r);const gate={promise,release,started,seen};gates.set(key,gate);return gate;}
async function delayed(key){const gate=gates.get(key);if(gate){gates.delete(key);gate.started();await gate.promise;}}
const project={name:'demo',observed_at:1,session_count:1,setup:{state:'ready',observed_at:1},app:{state:'not_deployed'},attention:{items:[]},jobs:{items:[{name:'alpha',cron:'daily',state:'not_run'},{name:'beta',cron:'daily',state:'not_run'}]}};
const server=http.createServer(async(req,res)=>{try{
 let text='';for await(const c of req)text+=c;const u=new URL(req.url,'http://fixture');
 const send=(body,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body));};
 if(u.pathname==='/browser/session'){await delayed('session');return send({identity:{display_name:'review fixture'},csrf_token:'fixture'});}
 if(u.pathname==='/browser/api/overview')return send({observed_at:1,inventory_revision:'fixture',projects:{items:[project],total:1,next_offset:null},attention:{items:[{project:'demo',source:'project:demo/setup',code:'repository_pending'}],total:1}});
 if(u.pathname.includes('/work-items')){const id=u.pathname.split('/')[6];if(req.method==='POST'||req.method==='PATCH'){
  const body=JSON.parse(text);writes.push({method:req.method,id,body});let item;
  if(req.method==='POST'){item={...row(body.id,body.fields.title),...body.fields};rows.push(item);}else{item=rows.find(x=>x.id===id);if(item.revision!==body.expected_revision)return send({error:'work_item_revision_conflict'},409);Object.assign(item,body.fields,{revision:item.revision+1});}
  const saved=structuredClone(item);await delayed('save');return send(saved,req.method==='POST'?201:200);
 }if(id){const snapshot=structuredClone(rows.find(r=>r.id===id));await delayed('item:'+id);return send(snapshot);}return send({items:rows,total:rows.length,offset:0,next_offset:null});}
 if(u.pathname.includes('/jobs/')){const name=u.pathname.split('/')[6];await delayed('job:'+name);return send({items:[],total:0,offset:0,next_offset:null});}
 if(u.pathname.startsWith('/browser/api/projects/'))return send(project);
 const name=u.pathname.startsWith('/browser/assets/')?u.pathname.split('/').pop():'index.html';res.writeHead(200,{'content-type':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html'});res.end(fs.readFileSync(path.join(root,name)));
 }catch(e){res.writeHead(500);res.end(String(e));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.SIGIL_BROWSER_EXECUTABLE?{executablePath:process.env.SIGIL_BROWSER_EXECUTABLE}:{})});let failed=0;
 async function run(name,fn){rows=[row('a','Item A'),row('b','Item B')];gates=new Map();writes=[];const page=await browser.newPage();page.setDefaultTimeout(3000);try{await fn(page);console.log('PASS '+name);}catch(e){failed++;console.log('FAIL '+name+': '+e.message);}finally{for(const g of gates.values())g.release();await page.close();}}
 const pending=async p=>{await p.goto(base+'/ui/projects/demo/pending');await p.getByRole('button',{name:'Item A',exact:true}).waitFor();};
 const title=p=>p.getByLabel('Title',{exact:true});
 const finish=async(p,gate,url)=>{const response=p.waitForResponse(r=>r.url().includes(url));gate.release();await response;await p.waitForTimeout(80);};
 await run('I1 update preserves edits during session check and save; next save and navigation',async p=>{await pending(p);await p.getByRole('button',{name:'Item A',exact:true}).click();await title(p).fill('submitted');const session=hold('session'),save=hold('save');await p.getByRole('button',{name:'Save work item',exact:true}).click();await session.seen;await title(p).fill('typed during session check');session.release();await save.seen;await title(p).fill('typed during save');await finish(p,save,'/work-items/a');assert.equal(await title(p).inputValue(),'typed during save');assert.match(await p.locator('.form-status').innerText(),/unsaved/i);const retained=await title(p).inputValue();await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();assert.equal(await title(p).inputValue(),retained);assert.match(await p.locator('.form-status').innerText(),/unsaved/i);await p.getByRole('button',{name:'Save work item',exact:true}).click();await p.getByText('Saved revision 3.',{exact:true}).waitFor();assert.equal(writes[1].body.fields.title,'typed during save');await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();assert.equal(await title(p).inputValue(),'typed during save');});
 await run('I1 create preserves newer fields and next save updates created identity',async p=>{await pending(p);await title(p).fill('created submitted');const session=hold('session'),save=hold('save');await p.getByRole('button',{name:'Save work item',exact:true}).click();await session.seen;await title(p).fill('created during session');session.release();await save.seen;await title(p).fill('created during save');await finish(p,save,'/work-items');assert.equal(await title(p).inputValue(),'created during save');assert.match(await p.locator('.form-status').innerText(),/unsaved/i);const retained=await title(p).inputValue();await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();assert.equal(await title(p).inputValue(),retained);assert.match(await p.locator('.form-status').innerText(),/unsaved/i);await p.getByRole('button',{name:'Save work item',exact:true}).click();await p.getByText('Saved revision 2.',{exact:true}).waitFor();assert.equal(writes[1].method,'PATCH');assert.equal(writes[1].body.fields.title,'created during save');await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();assert.equal(await title(p).inputValue(),'created during save');});
 for(const newer of [true,false])await run('I1 return before create completes; newer input='+newer,async p=>{
  await pending(p);await title(p).fill('create submitted');const save=hold('save');
  await p.getByRole('button',{name:'Save work item',exact:true}).click();await save.seen;
  const createdId=writes[0].body.id;
  await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();
  if(newer)await title(p).fill('newer return draft');
  await title(p).focus();await title(p).evaluate(e=>e.setSelectionRange(2,5));
  const field=await title(p).elementHandle();await finish(p,save,'/work-items');
  assert.equal(await field.evaluate(e=>e.isConnected&&e===document.activeElement),true,'completion must preserve the current field and focus');
  assert.deepEqual(await title(p).evaluate(e=>[e.selectionStart,e.selectionEnd]),[2,5]);
  const wanted=newer?'newer return draft':'create submitted';assert.equal(await title(p).inputValue(),wanted);
  const response=p.waitForResponse(r=>r.url().includes('/work-items')&&r.request().method()!=='GET');
  await p.getByRole('button',{name:'Save work item',exact:true}).click();await response;
  assert.equal(writes[1].method,'PATCH');assert.equal(writes[1].id,createdId);assert.equal(writes[1].body.expected_revision,1);
  await p.getByText('Saved revision 2.',{exact:true}).waitFor();
  assert.equal(rows.filter(r=>r.id===createdId).length,1);assert.equal(rows.find(r=>r.id===createdId).title,wanted);assert.equal(rows.find(r=>r.id===createdId).revision,2);
  await p.getByRole('link',{name:'Workspace',exact:true}).click();await p.goBack();assert.equal(await title(p).inputValue(),wanted);
 });
 await run('I2 later item selection wins out-of-order reads',async p=>{await pending(p);const a=hold('item:a');await p.getByRole('button',{name:'Item A',exact:true}).click();await a.seen;await p.getByRole('button',{name:'Item B',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[name=title]')?.value==='Item B');await title(p).fill('B draft');await finish(p,a,'/work-items/a');assert.equal(await title(p).inputValue(),'B draft');assert.equal(new URL(p.url()).searchParams.get('item'),'b');});
 await run('I2 New item invalidates a pending item read',async p=>{await pending(p);const a=hold('item:a');await p.getByRole('button',{name:'Item A',exact:true}).click();await a.seen;await p.getByRole('button',{name:'New item',exact:true}).click();await title(p).fill('New draft');await finish(p,a,'/work-items/a');assert.equal(await title(p).inputValue(),'New draft');assert.equal(new URL(p.url()).searchParams.get('item'),null);});
 await run('I2 delayed create does not replace a later selected item',async p=>{await pending(p);await title(p).fill('create in flight');const save=hold('save');await p.getByRole('button',{name:'Save work item',exact:true}).click();await save.seen;await title(p).fill('newer create draft');await p.getByRole('button',{name:'Item B',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[name=title]')?.value==='Item B');await finish(p,save,'/work-items');assert.equal(new URL(p.url()).searchParams.get('item'),'b');assert.equal(await title(p).inputValue(),'Item B');await p.getByRole('button',{name:'create in flight',exact:true}).click();assert.equal(await title(p).inputValue(),'newer create draft');});
 await run('I2 delayed create never navigates a later page; draft survives return',async p=>{await pending(p);await title(p).fill('create then navigate');const save=hold('save');await p.getByRole('button',{name:'Save work item',exact:true}).click();await save.seen;await title(p).fill('newer navigation draft');await p.getByRole('link',{name:'Workspace',exact:true}).click();await finish(p,save,'/work-items');assert.match(p.url(),/\/workspace$/);await p.goBack();assert.equal(await title(p).inputValue(),'newer navigation draft');await p.getByRole('button',{name:'Save work item',exact:true}).click();await p.getByText('Saved revision 2.',{exact:true}).waitFor();assert.equal(writes[1].method,'PATCH');});
 await run('I2 later job history selection wins out-of-order reads',async p=>{await p.goto(base+'/ui/projects/demo/jobs');await p.getByRole('button',{name:'View history',exact:true}).first().waitFor();const a=hold('job:alpha');await p.getByRole('button',{name:'View history',exact:true}).first().click();await a.seen;await p.getByRole('button',{name:'View history',exact:true}).nth(1).click();await p.getByRole('heading',{name:'beta history'}).waitFor();await finish(p,a,'/jobs/alpha/runs');assert.equal(await p.locator('#job-history h3').innerText(),'beta history');});
 await run('M1 keyboard skip link focuses main',async p=>{await p.goto(base+'/ui/overview');await p.getByRole('heading',{name:'Overview',exact:true}).waitFor();await p.keyboard.press('Tab');assert.equal(await p.locator('.skip').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await p.locator('#main').evaluate(e=>e===document.activeElement),true);});
 await run('M2 attention and active-work links retain focus on polling',async p=>{await p.goto(base+'/ui/overview');await p.locator('#attention a').waitFor();for(const selector of ['#attention a','#active a']){await p.locator(selector).focus();const response=p.waitForResponse(r=>r.url().includes('/browser/api/overview'));await p.evaluate(()=>document.getElementById('refresh').click());await response;await p.waitForTimeout(80);assert.equal(await p.locator(selector).evaluate(e=>e===document.activeElement),true,selector);}});
 await browser.close();server.close();if(failed)process.exitCode=1;console.log(`${11-failed}/11 review regressions passed`);
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
