// Actual shared browser assets against bounded fake exact-contract services only.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {createRequire}=require('node:module');const {chromium}=createRequire(process.env.SIGIL_PLAYWRIGHT_PACKAGE)('playwright');
const root=path.resolve(__dirname,'../src/browser/assets'),out=path.resolve('target/b3b-screenshots');fs.mkdirSync(out,{recursive:true});
let definiteReject=false,showProjection=false;const summaryProjection=JSON.parse(fs.readFileSync('sigiledd/target/b3b-fix1-summary-projection.json','utf8'));
let stagePosts=0,handoffPosts=0;let auth=true,ready=true,createCount=0,keys=[],lastBody=null,researchDelay=null,sessionDelay=null;
const project={name:'atlas',display_name:'Atlas',description:'Research project',session_count:0,setup:{state:'ready'},capabilities:{},app:{state:'not_deployed'},jobs:{items:[],total:0},sessions:{items:[],total:0},attention:{items:[],total:0},activity:{items:[],total:0},observed_at:1789012800};
const record=id=>({run_id:id,problem:id==='run1'?'Design a calmer workbench':'Other research',status:'done',created_at:'2026-09-10T00:00:00Z',updated_at:'2026-09-10T00:00:01Z',revision:'9007199254740993',association:{project:'atlas'},stages:[{stage:'categorize',status:'done',computed_by:'genie:fixture/s'},{stage:'breadth',status:'skipped',detail:'Search unavailable'},{stage:'converge',status:'done',computed_by:'caller'}],artifacts:{arxiv_only:true,corpus:[{title:'<img src=x onerror=alert(1)>',url:'javascript:alert(1)'}],outcome:id==='run2'?{decision:'fixture decision'}:null,dossier:'# Dossier\n[unsafe](javascript:alert(1))',adhd_run_id:'adhd1'},awaiting:null,catalog_attempts:[{catalog_version:1,freshness:'fresh'}],handoff_available:id==='run2'});
const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,'http://fixture');let raw='';for await(const c of req)raw+=c;
 const reply=(v,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(v));};
 if(u.pathname==='/browser/session'){if(sessionDelay)await sessionDelay;return reply(auth?{identity:{display_name:'Research fixture'},actor:{driver:'human:fixture'},csrf_token:'csrf'}:{error:'login_required'},auth?200:401);}
 if(u.pathname.startsWith('/browser/api/')){
  if(!auth)return reply({error:'login_required'},401);
  if(req.method==='POST')assert.equal(req.headers['x-sigil-csrf'],'csrf');
  if(u.pathname==='/browser/api/projects/atlas')return reply(project);
  if(u.pathname==='/browser/api/research'&&showProjection)return reply(summaryProjection);
  if(u.pathname==='/browser/api/research')return reply({state:'observed',readiness:ready?'ready':'update_or_storage_repair_required',observed_at:1789012800,runs:[record('run1'),record('run2')],next_cursor:null});
  if(u.pathname.endsWith('/research/operations'))return reply({operations:[]});
  if(u.pathname==='/browser/api/projects/atlas/research'&&req.method==='POST'){createCount++;lastBody=JSON.parse(raw);keys.push(lastBody.operation_id);if(definiteReject){definiteReject=false;return reply({error:'invalid_research_options'},400);}if(researchDelay){await researchDelay;}if(createCount===1)return reply({error:"service_unavailable"},503);return reply({run_id:'run1',operation_id:lastBody.operation_id,state:'accepted'});}
  if(u.pathname==='/browser/api/research/run1/adhd')return reply({adhd_run_id:'adhd1',record:{state:'done',ideas:['A recorded idea']}});
  if(u.pathname==='/browser/api/research/run1'&&req.method==='POST'){const body=JSON.parse(raw);assert.equal(body.expected_revision,'9007199254740993');assert.equal(body.action,'converge');stagePosts++;return reply({revision:'9007199254740994'});}
  if(u.pathname==='/browser/api/projects/atlas/ide')return reply({session_id:'fixture',generation:'18446744073709551615'});
  if(u.pathname==='/browser/api/research/run2/handoff'){if(req.method==='POST'){const b=JSON.parse(raw);assert.equal(b.generation,'18446744073709551615');assert.equal(b.bundle_digest,'fixture-digest');handoffPosts++;return reply({commit:'a'.repeat(40),dirty:false,state:'committed_on_session'});}return reply({project:'atlas',bundle:{digest:'fixture-digest',files:[{path:'docs/design/fixture/dossier.md',content:'# Approved dossier'},{path:'docs/design/fixture/cover.md',content:'Original problem'}]}});}
  if(u.pathname.startsWith('/browser/api/research/')){const id=u.pathname.split('/')[4];if(id==='run1'&&u.searchParams.get('slow'))await new Promise(r=>setTimeout(r,100));return reply(record(id));}
  if(u.pathname==='/browser/api/models')return reply({observed_at:1789012800,status:{state:'observed',data:{slots:[{provider:'fixture',size:'s',kind:'external',model:'Model fixture',downloaded:true,loaded:false}],lock:null}},info:{state:'unavailable'},usage:{state:'observed',data:{entries:[{provider:'fixture',size:'s',model:'Model fixture',ts_ms:1789012800000,input_tokens:null,output_tokens:0,status:200}]}}});
  return reply({error:'fixture_not_found'},404);
 }
 const name=u.pathname.startsWith('/browser/assets/')?path.basename(u.pathname):'index.html';const type=name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html';res.writeHead(200,{'content-type':type});res.end(fs.readFileSync(path.join(root,name)));
 }catch(e){res.writeHead(500);res.end(String(e));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:980}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
try{
 await page.goto(base+'/ui/projects/atlas/research');await page.getByLabel('Problem',{exact:true}).waitFor();await page.getByRole('button',{name:'Start research',exact:true}).waitFor();
 await page.getByLabel('Problem',{exact:true}).fill('   ');await page.getByRole('button',{name:'Start research',exact:true}).click();await page.getByText('Research was not started.',{exact:false}).waitFor();assert.equal(createCount,0);
 await page.getByLabel('Problem',{exact:true}).fill('😀'.repeat(10000));await page.getByRole('button',{name:'Start research',exact:true}).click();assert.equal(createCount,0);
 await page.getByLabel('Problem',{exact:true}).fill('Corrected problem');await page.getByLabel('Context',{exact:true}).fill('é'.repeat(20000));await page.getByRole('button',{name:'Start research',exact:true}).click();assert.equal(createCount,0);
 await page.getByLabel('Context',{exact:true}).fill('Corrected context');definiteReject=true;await page.getByRole('button',{name:'Start research',exact:true}).click();await page.waitForTimeout(100);assert.equal(createCount,1);await page.getByRole('button',{name:'Start research',exact:true}).waitFor();
 await page.getByLabel('Problem',{exact:true}).fill('Deliberately corrected after rejection');await page.getByRole('button',{name:'Start research',exact:true}).click();await page.getByRole('button',{name:'View run',exact:true}).waitFor();assert.equal(createCount,2);assert.equal(lastBody.problem,'Deliberately corrected after rejection');assert.equal(lastBody.context,'Corrected context');assert.notEqual(keys[0],keys[1]);
 createCount=0;keys=[];lastBody=null;await page.goto(base+'/ui/projects/atlas/research');await page.getByLabel('Problem',{exact:true}).waitFor();
 await page.getByLabel('Problem',{exact:true}).fill('My problem');await page.getByLabel('Context',{exact:true}).fill('Keep this context');
 let release,releaseAuth;sessionDelay=new Promise(r=>releaseAuth=r);researchDelay=new Promise(r=>release=r);await page.getByRole('button',{name:'Start research',exact:true}).click();await page.waitForTimeout(100);
 await page.getByLabel('Context',{exact:true}).fill('Newer context');releaseAuth();sessionDelay=null;await page.waitForTimeout(100);assert.equal(await page.getByRole('button',{name:'Start research',exact:true}).isDisabled(),true);release();researchDelay=null;await page.getByRole('button',{name:'Retry start',exact:true}).waitFor();assert.equal(createCount,1);assert.equal(await page.getByLabel('Context',{exact:true}).inputValue(),'Newer context');assert.equal(lastBody.context,'Keep this context');
 auth=false;await page.getByRole('button',{name:'Retry start',exact:true}).click();await page.getByRole('link',{name:'Sign in in another tab'}).waitFor();auth=true;const before=createCount;await page.getByRole('button',{name:'Check sign-in',exact:true}).click();await page.getByRole('button',{name:'Retry start',exact:true}).waitFor();assert.equal(createCount,before);await page.getByRole('button',{name:'Retry start',exact:true}).click();await page.waitForTimeout(100);assert.equal(createCount,2);assert.equal(keys[0],keys[1]);assert.equal(lastBody.context,'Keep this context');
 await page.getByRole('button',{name:'View run',exact:true}).click();await page.getByRole('heading',{name:'Design a calmer workbench',exact:true}).waitFor();await page.getByText('Stages finished without a decision.',{exact:false}).waitFor();assert.equal(await page.locator('img').count(),0);await page.getByText('Dossier',{exact:true}).click();assert.equal(await page.locator('a[href^="javascript:"]').count(),0);await page.getByRole('button',{name:'Inspect ADHD run adhd1',exact:true}).click();await page.getByText('Recorded ADHD detail',{exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'research-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'research-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByText('Submit an existing converge result',{exact:true}).click();await page.getByLabel('Stage result JSON').fill('{"fixture":true}');await page.getByRole('button',{name:'Submit stage result',exact:true}).click();await page.waitForTimeout(100);assert.equal(stagePosts,1);
 await page.goto(base+'/ui/research?run=run2');await page.getByRole('button',{name:'Preview project handoff',exact:true}).click();await page.getByRole('button',{name:'Pause editor and commit dossier',exact:true}).click();await page.getByText('Master acceptance and memory indexing are still pending.',{exact:false}).waitFor();assert.equal(handoffPosts,1);assert.equal(await page.getByRole("button",{name:"Dossier committed",exact:true}).isDisabled(),true);await page.screenshot({path:path.join(out,'handoff-mobile.png'),fullPage:true});
 await page.goto(base+'/ui/models');await page.getByText('Recent observation window.',{exact:false}).waitFor();await page.getByText('Unknown',{exact:true}).waitFor();assert.match(await page.locator("#connection").textContent(),/Observed .*unavailable/);await page.getByRole('cell',{name:'0',exact:true}).waitFor();await page.screenshot({path:path.join(out,'models-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 showProjection=true;await page.goto(base+'/ui/research');await page.getByRole('button',{name:'Echoed [redacted]',exact:true}).waitFor();assert.equal((await page.locator('body').textContent()).includes('fixture-summary-bearer'),false);showProjection=false;
 ready=false;await page.goto(base+'/ui/projects/atlas/research');await page.getByText('Research service update or storage repair required before starting or resuming.',{exact:false}).waitFor();assert.equal(await page.getByRole('button',{name:'Start research',exact:true}).isDisabled(),true);assert.equal(createCount,2);
 assert.deepEqual(errors,[]);console.log('PASS: real adapter summary projection contains no echoed bearer; whitespace/UTF-8 preflight and definite rejection corrected deliberately; ambiguous retry identity retained; real assets, research navigation, option form, double-click exclusion, submitted/newer draft retention, fresh login without replay, stable operation retry, exact revision surface, no-decision/degraded separation, ADHD linkage, safe text, unknown/zero usage, old-service gating, mobile/desktop screenshots');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
